### ISSUE TITLE
Week 6 ready for review

### ISSUE THREAD

**Issue by whurd20** [whurd20/carHacker#3]
@pawaitemadisoncollege week 6 is done.

http://18.191.42.207:8080/carHacker/

The screenshot is in my screenshots folder for this repo, I couldn't figure out how to get it right here in the issue.

a) This is the second time I've done deployment, I did it in AdvPHP as well. It is very gratifying. Using the tomcat manager app is so much easier than using the terminal/ssh to send files from your development VM to your deployment VM.

b/c) I only had a minor challenge in using PuTTy, This video helped.
https://www.google.com/search?q=putty+aws+login+as&oq=putty+aws+login+&aqs=chrome.0.0j69i57j0i22i30.3111j1j7&sourceid=chrome&ie=UTF-8#kpvalbx=_2ZdCYK_iBdCntQbP4JWgCA24

**Comment by pawaitemadisoncollege** [comment]
Nicely done! Isn't it nice to see your java web app out there for all to access?!

For future work, you can add images to issues with a drag and drop! 

![Screen Shot 2021-03-06 at 4 44 16 PM](https://user-images.githubusercontent.com/13874466/110222894-5a015700-7e9b-11eb-93f2-0f013d77e6b0.png)

**Comment by whurd20** [comment]
Ok, lol I tried but it just put up like a url.

**Comment by pawaitemadisoncollege** [comment]
Yes! The source will look like a url, but when you preview it you should see the actual image.
